dist: trusty
language: php
services:
- mysql
php:
  - 5.6
  - 7.0
  - 7.1

sudo: required

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cp .env.travis .env
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - composer check-style
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi